### ISSUE TITLE
Can pair_nequip be implemented as a plugin to LAMMPS?

### ISSUE THREAD

**Issue by CompRhys** [mir-group/pair_nequip#5]
LAMMPS has plugin functionality that allows new functionality to be added without the need to recompile and link everything - https://docs.lammps.org/plugin.html

Have the authors investigated whether or not Nequip can be interfaced as a plugin and if so were there any reasons that you avoided this approach? For example, would there be any expected issues if I ran a serial calculation with a nequip plugin on a build of LAMMPS compiled to allow MPI calculations?

**Comment by anjohan** [comment]
Hi Rhys,

I think the plugin functionality is fairly new, and I have no experience with it. What would be the main benefit?

Implementing pair styles and dumping them in `src/` still seems like the standard approach, so this is what I went with.
This also has the advantage of exploiting LAMMPS' existing build system instead of having to set up a new one (and why compile two things instead of one?). You'll have to compile LAMMPS anyways, and it shouldn't take more than a minute.

At some point, when the code is more stable, we may try to get it into the main LAMMPS repo as an ML-NEQUIP package.

As for MPI: A serial run with an MPI build should always be fine, as long as you do `mpirun -np 1` or avoid `mpirun` entirely.

Best wishes,
Anders

**Comment by CompRhys** [comment]
We're looking at offering multiple MLFF and so having a single build of LAMMPS with `-D PKG_PLUGIN` rather than having to recompile the central LAMMPS package each time and having to patch the source for each additional model we explore seems like a slightly cleaner solution if available.

I think the plugin functionality is about a year old so yep not yet standard but perhaps longer term it seems as though it's a better solution than copying sources?

**Comment by anjohan** [comment]
Right, that makes sense. But I don't think it's our priority right now, unless someone has a burning desire to implement it. I would also be mildly worried about linking issues and a (currently) less familiar installation procedure.

According to `find $HOME -name lammps.cpp`, I just have 11 LAMMPS directories with ~18 build directories across two machines.

**Comment by CompRhys** [comment]
> Right, that makes sense. But I don't think it's our priority right now, unless someone has a burning desire to implement it.

If I can get time for it I might try. I am new to using LAMMPS so could be good for getting under the hood.
